%% salaryBySpecialty

% Housekeeping
clear

% The source of the data to be plotted
sourceStr{1} = 'AAMC Faculty Salary Report, FY 2019, table 11';

% Instantiate a plotlab object
plotlabOBJ = plotlab();

% Apply the default plotlab recipe 
% overriding just the figure size
plotlabOBJ.applyRecipe(...
  'figureWidthInches', 10, ...
  'figureHeightInches', 6);

% Create a figure
figHandle = figure();

% Load "table11_rports_valid.xlsx". Silence the typical warnings
warnState = warning();
warning('off','MATLAB:table:ModifiedAndSavedVarnames');
filePathBits = strsplit(fileparts(mfilename('fullpath')),filesep);
tableName = fullfile(filesep,filePathBits{1:end-1},'data','table11_rports_valid.xlsx');
table = readtable(tableName);
warning(warnState);

% Define here lists of specialities. These are the labels on the plot
specialities_labels = {...
    'Orthopaedics',...
    'Cardiology',...
    'Anesthesiology',...
    'Dermatology',...
    'Family Medicine',...
    'OB/GYN',...
    'Pathology',...
    'Pediatrics',...
    'Psychiatry',...
    'Radiology',...
    'Neurology - Adult',...
    'Neurology - Peds',...
    'Intensive Care',...
    'Emergency Medicine',...
    'General Surgery',...
    'ENT',...
    'Vascular Surgery',...
    'Radiation Oncology',...
    'Rheumatology',...
    'Ophthalmology',...
    'Rehab',...
    };

% This is how these are marked in the table
specialities_cats = {'Orthopedic Surgery: Total',...
    'Cardiology: Total',...
    'Total Anesthesiology',...
    'Total Dermatology',...
    'Total Family Medicine',...
    'Total OB/GYN',...
    'Total Pathology',...
    'Total Pediatrics',...
    'Total Psychiatry',...
    'Total Radiology',...
    'Neurology',...
    'Neurology-Peds.',...
    'Critical/Intensive Care-Med.',...
    'Emergency Medicine',...
    'General Surgery',...
    'Otolaryngology',...
    'Vascular Surgery',...
    'Radiation Oncology',...
    'Rheumatology-Med.',...
    'Ophthalmology',...
    'Physical Medicine & Rehabilitation',...
    };   

% Loop through the specialties and get the mean salary across ranks (asst
% to full)
for ii = 1:length(specialities_cats)
    idx = find(strcmp(table.Department_Specialty,specialities_cats{ii}));
    rankCounts = table.Count(idx(2:4));
    medians = table.Median(idx(2:4));
    weights = rankCounts / sum(rankCounts);
    salVal(ii) = sum(medians.*weights)./sum(weights);
end

% Sort salary and labels highest to lowest
[salVal,sortOrder] = sort(salVal);
labels = reordercats(categorical(specialities_labels(sortOrder)),specialities_labels(sortOrder));

% Plot
barh(labels,salVal,0.25);
box off
xlim([0 600]);
xlabel('Salary [$k]');

% Add text entries for the $ values
for ii = 1:length(specialities_cats)
text(salVal(ii)+30,labels(ii),cur2str(salVal(ii)*1000));
end

% Add title and labels
% Add title
str = {['\fontsize{16}', 'Median academic salary across ranks [asst, assoc, full] by specialty'];...
        ['\fontsize{8}\color{blue} ' sourceStr{1} ]};
title(str);

